### PR TITLE
fix: respect noExternal option with Tsup node

### LINKED ISSUE #718: "tsup-node" doesn't respect "noExternal" configuration
Hi,

I've been using "[tsup-node to exclude all packages](https://tsup.egoist.dev/#excluding-all-packages)" with great pleasure to build some scripts while excluding all node_modules.

I am refactoring a monorepo, and I am in the special case where I have internal NPM packages that expose pure .ts code.
Therefore, I need those specific packages to be included in the build, despite being listed in the package.json.

The use case is pretty close to what's described for next-transpile-modules: https://www.npmjs.com/package/next-transpile-modules "code transpilation from local packages (think: a monorepo with a styleguide package)". 

What's the equivalent in Tsup? How can we forcibly reinclude some packages while using tsup-node?

Here is an example: https://github.com/Devographics/Monorepo/pull/117, the scripts are built in the "surveyform" directory, alongside the Next app. Package "core-models" lives in the shared folder, you can see how the package.json let's us expose pure TS files. I need this specific package to be bundled despite it being listed in package.json as a dependency.

### PR DESCRIPTION
**Pull request by eric-burel**
Fixes #718 

/!\ I haven't tested if it still builds (but I only touched 2 lines of code) + this might be a slight breaking change if some people use `tsup-node` and accidentally had a  "noExternal" option set (before this PR, the noExternal would be ignored, after this PR, it is correctly considered thus bundling more packages).

### CODE REVIEW

File: src/esbuild/external.ts [hunk 1]
```diff
@@ -28,6 +28,9 @@ export const externalPlugin = ({
           if (match(args.path, resolvePatterns)) {
             return
           }
+          if (match(args.path, noExternal)) {
```
Comment (VladimirGrenaderov) [inline src/esbuild/external.ts:31]: The same logic repeats in second onResolve callback: https://github.com/egoist/tsup/blob/d074dd9c33adf85bcd149e79c9d141517a956ce0/src/esbuild/external.ts#L41 Looks like branching shall be implemented inside single callback:
```ts
match(args.path, noExternal)
if (skipNodeModulesBundle) {
  match(args.path, resolvePatterns)
  NON_NODE_MODULE_RE.test(args.path)
}
match(args.path, external)

**Review by VladimirGrenaderov — CHANGES_REQUESTED** [review]

**Comment by eric-burel** [comment]
@VladimirGrenaderov here is a factored version of the code however I am not sure if it's an improvement, you may want a callback as tiny as possible because it will be called many times. 
So in this PR I'd rather stick to fixing tsup-node, and avoid changes that could affect perfs negatively.

Factored version just in case, but again I am not a big fan:
```ts
build.onResolve({ filter: /.*/ }, (args) => {
        // Respect explicit options for specific packages
        if (match(args.path, noExternal)) {
          return
        }
        if (match(args.path, external)) {
          return { external: true }
        }
        if (skipNodeModulesBundle) {
          const resolvePatterns = tsconfigPathsToRegExp(
            tsconfigResolvePaths || {}
          )
          // Resolve `paths` from tsconfig
          if (match(args.path, resolvePatterns)) {
            return
          }
          // every other import that looks like a node_modules is external
          if (NON_NODE_MODULE_RE.test(args.path)) {
            return {
              path: args.path,
              external: true,
            }
          }
        }
      })
```

**Comment by VladimirGrenaderov** [comment]
@eric-burel I meant that 'match(...)' call is not free (regexps as so slow, you know), and we shall not repeat similar calls im multiple callbacks. It's ok for me to have atomic callbacks, but not at the cost of an obvious performance degradation.

Sure, as 'one line fix' this PR is good and much more safer. And it's only package maintainers decision.

**Comment by eric-burel** [comment]
@VladimirGrenaderov You are totally I right I misunderstood you're initial comment. I've committed a new version that will register only one callback depending on the scenario.

So the initial logic was correct, except for a minor priority issue: anything looking like a node_module was treated as external before the code reached the "noExternal" condition when the skip option was true. This PR aims to fix that and has a more explicit if/else.

Thanks for your help!

**Review by VladimirGrenaderov — APPROVED** [review]
